import { Service } from "@/types/services";

export const ServiceListData: Service[] = [
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
    notifications: true,
  },
  {
    service: "hci",
    url: "https://hci.tlu.ee/",
    platform: "WordPress",
    version: "10",
    server: "sensitive",
    location: "sensitive",
    contact: "Iuulia",
    client: "Ilja",
    comment: "koik tootab",
  },
  {
    service: "hci",
    url: "https://hci.tlu.ee/",
    platform: "WordPress",
    version: "10",
    server: "sensitive",
    location: "sensitive",
    contact: "Iuulia",
    client: "Ilja",
    comment: "koik tootab",
  },
  {
    service: "hci",
    url: "https://hci.tlu.ee/",
    platform: "WordPress",
    version: "10",
    server: "sensitive",
    location: "sensitive",
    contact: "Iuulia",
    client: "Ilja",
    comment: "koik tootab",
  },
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
  },
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
  },
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
  },
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
  },
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
  },
  {
    service: "Edidaktikum",
    url: "https://edidaktikum.ee/",
    platform: "Drupal",
    version: "8.8.12",
    server: "sensitive",
    location: "sensitive",
    contact: "Pjotr",
    client: "Priit",
  },
];
